[libraries]
fmf.files = [
  "submodules/fmf/*.vhd",
]
interface_lib.files = [
  "submodules/icestick-uart/hdl/*.vhd",
  "submodules/sdram-fpga/sdram.vhd",
  "submodules/ulx3s-misc/examples/ecp5pll/hdl/vhd/ecp5pll.vhd",
]
util.files = [
  "src/util/*.vhd",
]
window_ctrl_lib.files = [
  "src/window_ctrl/*.vhd",
]
bnn_lib.files = [
  "src/*.vhd",
]